[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'Shougo/deoplete-clangx'
on_ft = ['c', 'cpp', 'cmake']

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1
on_ft = ['ruby']

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
on_ft = ['ruby']
build = 'bash install.sh'
rev = 'next'
hook_source = '''
set hidden
let g:LanguageClient_serverCommands = {
    \ 'ruby': ['solargraph', 'stdio'],
    \ }
let g:LanguageClient_autoStart = 1
nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
'''
